// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2);
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCompletedDownloads() {
  return window['go']['main']['App']['ClearCompletedDownloads']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearOldHistory(arg1) {
  return window['go']['main']['App']['ClearOldHistory'](arg1);
}

export function DownloadDeno() {
  return window['go']['main']['App']['DownloadDeno']();
}

export function ExportHistory() {
  return window['go']['main']['App']['ExportHistory']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetHistoryStats() {
  return window['go']['main']['App']['GetHistoryStats']();
}

export function GetJSRuntimeInfo() {
  return window['go']['main']['App']['GetJSRuntimeInfo']();
}

export function GetQueueStatus() {
  return window['go']['main']['App']['GetQueueStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetYtDlpVersion() {
  return window['go']['main']['App']['GetYtDlpVersion']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PauseAllDownloads() {
  return window['go']['main']['App']['PauseAllDownloads']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function RedownloadFromHistory(arg1) {
  return window['go']['main']['App']['RedownloadFromHistory'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function ResumeAllDownloads() {
  return window['go']['main']['App']['ResumeAllDownloads']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StopAllDownloads() {
  return window['go']['main']['App']['StopAllDownloads']();
}

export function StopDownload(arg1) {
  return window['go']['main']['App']['StopDownload'](arg1);
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}
