// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {updater} from '../models';
import {history} from '../models';
import {jsruntime} from '../models';
import {downloader} from '../models';
import {config} from '../models';

export function AddDownload(arg1:string,arg2:main.DownloadOptions):Promise<string>;

export function BrowseFolder():Promise<string>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function ClearCompletedDownloads():Promise<number>;

export function ClearHistory():Promise<void>;

export function ClearOldHistory(arg1:number):Promise<number>;

export function DownloadDeno():Promise<void>;

export function ExportHistory():Promise<string>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetClipboard():Promise<string>;

export function GetHistory(arg1:main.HistoryFilter):Promise<Array<history.Entry>>;

export function GetHistoryStats():Promise<Record<string, any>>;

export function GetJSRuntimeInfo():Promise<jsruntime.RuntimeInfo>;

export function GetQueueStatus():Promise<Array<downloader.Item>>;

export function GetSettings():Promise<config.Settings>;

export function GetYtDlpVersion():Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PauseAllDownloads():Promise<number>;

export function PauseDownload(arg1:string):Promise<void>;

export function RedownloadFromHistory(arg1:string):Promise<string>;

export function RemoveDownload(arg1:string):Promise<void>;

export function ResumeAllDownloads():Promise<number>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function StopAllDownloads():Promise<number>;

export function StopDownload(arg1:string):Promise<void>;

export function UpdateYtDlp():Promise<void>;
