// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2);
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function BrowseInputFile() {
  return window['go']['main']['App']['BrowseInputFile']();
}

export function BrowseMultipleInputFiles() {
  return window['go']['main']['App']['BrowseMultipleInputFiles']();
}

export function BrowseOutputFile(arg1) {
  return window['go']['main']['App']['BrowseOutputFile'](arg1);
}

export function CancelBatchConversion() {
  return window['go']['main']['App']['CancelBatchConversion']();
}

export function CancelConversion() {
  return window['go']['main']['App']['CancelConversion']();
}

export function CancelSpotifyDownload() {
  return window['go']['main']['App']['CancelSpotifyDownload']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCompletedDownloads() {
  return window['go']['main']['App']['ClearCompletedDownloads']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearOldHistory(arg1) {
  return window['go']['main']['App']['ClearOldHistory'](arg1);
}

export function DownloadDeno() {
  return window['go']['main']['App']['DownloadDeno']();
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function DownloadSpotifyTracks(arg1) {
  return window['go']['main']['App']['DownloadSpotifyTracks'](arg1);
}

export function EstimateConversionSize(arg1) {
  return window['go']['main']['App']['EstimateConversionSize'](arg1);
}

export function ExportHistory() {
  return window['go']['main']['App']['ExportHistory']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetConversionPresets() {
  return window['go']['main']['App']['GetConversionPresets']();
}

export function GetFFmpegVersion() {
  return window['go']['main']['App']['GetFFmpegVersion']();
}

export function GetHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2);
}

export function GetHistoryStats() {
  return window['go']['main']['App']['GetHistoryStats']();
}

export function GetJSRuntimeInfo() {
  return window['go']['main']['App']['GetJSRuntimeInfo']();
}

export function GetQueueStatus() {
  return window['go']['main']['App']['GetQueueStatus']();
}

export function GetRecentCompletedDownloads() {
  return window['go']['main']['App']['GetRecentCompletedDownloads']();
}

export function GetRecentHistory(arg1) {
  return window['go']['main']['App']['GetRecentHistory'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSpotifyRuntimeInfo() {
  return window['go']['main']['App']['GetSpotifyRuntimeInfo']();
}

export function GetYtDlpVersion() {
  return window['go']['main']['App']['GetYtDlpVersion']();
}

export function HideFromQueue(arg1) {
  return window['go']['main']['App']['HideFromQueue'](arg1);
}

export function InstallSpotifyRuntime() {
  return window['go']['main']['App']['InstallSpotifyRuntime']();
}

export function IsFFmpegInstalled() {
  return window['go']['main']['App']['IsFFmpegInstalled']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileInFolder(arg1) {
  return window['go']['main']['App']['OpenFileInFolder'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PauseAllDownloads() {
  return window['go']['main']['App']['PauseAllDownloads']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function PreviewSpotifyURL(arg1) {
  return window['go']['main']['App']['PreviewSpotifyURL'](arg1);
}

export function ProbeFile(arg1) {
  return window['go']['main']['App']['ProbeFile'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function RemoveHistoryEntry(arg1) {
  return window['go']['main']['App']['RemoveHistoryEntry'](arg1);
}

export function ResumeAllDownloads() {
  return window['go']['main']['App']['ResumeAllDownloads']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartBatchConversion(arg1, arg2) {
  return window['go']['main']['App']['StartBatchConversion'](arg1, arg2);
}

export function StartConversion(arg1) {
  return window['go']['main']['App']['StartConversion'](arg1);
}

export function StopAllDownloads() {
  return window['go']['main']['App']['StopAllDownloads']();
}

export function StopDownload(arg1) {
  return window['go']['main']['App']['StopDownload'](arg1);
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}
